---
name: CI


on:
  push:
    workflow_dispatch:

jobs:
  build:
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: dojo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}